server:
  port: 3344

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lsh-hhh/spring-cloud-config-demo.git  # git 上仓库的名字
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  # 集群
#  instance:
#    instance-id: spring-cloud-config-server-3344  # 指定服务的id
#    prefer-ip-address: true # 使用ip地址注册